README.md

Not an essential change but best to keep the documentation up-to-date.

Update android-apt version

---

permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/ClassType.java
permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/ConstantsProvider.java
permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/PermissionsProcessor.java
permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/RuntimePermissionsAnnotatedElement.java
permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/TypeResolver.java
permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/Utils.java
permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/Validator.java
permissionsdispatcher-processor/src/test/java/permissions/dispatcher/processor/ClassTypeTest.java
permissionsdispatcher-processor/src/test/java/permissions/dispatcher/processor/PermissionsProcessorTest.java
permissionsdispatcher-processor/src/test/java/permissions/dispatcher/processor/ValidatorTest.java
permissionsdispatcher-processor/src/test/java/permissions/dispatcher/processor/data/Source.java

Changed @RuntimePermissions to TypeMirror-based class validation

---

processor/build.gradle

[WIP] Move back sourceCompatibility/targetCompatibility

---

library/src/main/android/permissions/dispatcher/PermissionUtils.java

Just modify to cache targetSdkVersion to static variable.
This method might be called plural times, so it would improve perfomance.

Modify to cache target sdk version.

---

README.md

Add third contributor.

---

lint/src/main/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetector.java
lint/src/main/java/permissions/dispatcher/PermissionsDispatcherIssueRegistry.java

see #59 and its [comment](https://github.com/hotchemi/PermissionsDispatcher/issues/59#issuecomment-181818458)

Add a lint for NeedsPermission and OnShowRationale

---

library/src/main/android/permissions/dispatcher/PermissionUtils.java

Add a workaround for RuntimeException when checking self permissions

---

library/src/main/java/permissions/dispatcher/NeedsPermission.java
library/src/main/java/permissions/dispatcher/OnNeverAskAgain.java
library/src/main/java/permissions/dispatcher/OnPermissionDenied.java
library/src/main/java/permissions/dispatcher/OnShowRationale.java
library/src/main/java/permissions/dispatcher/RuntimePermissions.java

Change to RetentionPolicy.CLASS

---

library/src/main/android/permissions/dispatcher/PermissionUtils.java

Fix problem with empty grantReults.

---

lint/src/main/java/permissions/dispatcher/CallOnRequestPermissionsResultDetector.java
lint/src/main/java/permissions/dispatcher/PermissionsDispatcherIssueRegistry.java

Fix lint onRequestPermissionsResult

---

README.md
library/build.gradle
library/proguard-rules.txt

Close #172 
I made draft for README. Feel free to comment on that!

Add ProGuard support

---

README.md

Needed for inner class button handling.

Make request final in README's showRationale example

---

library/src/main/android/permissions/dispatcher/PermissionUtils.java

ref: https://github.com/hotchemi/PermissionsDispatcher/issues/211
- This change will add workaround for Xiaomi.
- I referenced this method actually. https://github.com/a1018875550/PermissionDispatcher/blob/master/library/src/main/android/org.jokar.permissiondispatcher.library/PermissionUtils.java#L128

Add workaround for Xiaomi devices.

---

library/src/main/android/permissions/dispatcher/PermissionUtils.java

Use PermissionChecker's checkSelfPermission

---

library/src/main/android/permissions/dispatcher/PermissionUtils.java

- closes https://github.com/hotchemi/PermissionsDispatcher/issues/244
- Just in case user select the normal permission, fix to return true when `permissionToOp` returns null
- And change to use `AppOpsManagerCompat` instead of real `AppOpsManager`

Fix to use compat class.

---

README.md

Well, as you guys know already, I need English teachers to fix the "syntax".

Document hidden features

---

processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt
processor/src/test/java/permissions/dispatcher/processor/ProcessorTestSuite.java
processor/src/test/java/permissions/dispatcher/processor/data/Source.java
processor/src/testV13/java/permissions/dispatcher/processor/V13ProcessorTestSuite.java
processor/src/testV13/java/permissions/dispatcher/processor/data/V13Source.java

Change how to create the generated class package name

---

.github/ISSUE_TEMPLATE.md

I want to add FAQ section to ISSUE_TEMPLATE for handling the case of "XxxPermissionsDispatcher does not generated"
WDYT? @hotchemi @aurae

Add FAQ to ISSUE_TEMPLATE

---

.github/ISSUE_TEMPLATE.md

I updated the contents of @shiraji 's ISSUE_TEMPLATE. Basically, I reduced the Markdown in the first (FAQ) section, since it might be easier to read for users writing the issue.
Let me know what you think! :)

Updated ISSUE_TEMPLATE FAQs

---

processor/src/main/kotlin/permissions/dispatcher/processor/RuntimePermissionsElement.kt
processor/src/main/kotlin/permissions/dispatcher/processor/exception/DuplicatedMethodNameException.kt
processor/src/main/kotlin/permissions/dispatcher/processor/util/Validators.kt
processor/src/test/java/permissions/dispatcher/processor/ProcessorTestSuite.java
processor/src/test/java/permissions/dispatcher/processor/data/Source.java
processor/src/testV13/java/permissions/dispatcher/processor/V13ProcessorTestSuite.java
processor/src/testV13/java/permissions/dispatcher/processor/data/V13Source.java

Add compile-time check for NeedsPermission's overloaded methods

---

.github/ISSUE_TEMPLATE.md
README.md

- Fix a readme a bit.
- Comment out caution part of issue template.

Fix readme a bit.

---

doc/users.md

We are using PermissionsDispatcher in our app mitene. Thank you for great lib.

added mitene to users.md

---

sample-kotlin/build.gradle
sample-kotlin/src/main/res/layout/fragment_main.xml
sample/build.gradle
sample/src/main/res/layout/fragment_main.xml

Current sample project disable lint checks. Since we have some lint
checks in library, we should enable lint checks to enhance developers
use lint checks.

Make lint works again!

---

test-v13/src/test/java/permissions/dispatcher/test_v13/Extensions.kt
test-v13/src/test/java/permissions/dispatcher/test_v13/FragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
test-v13/src/test/java/permissions/dispatcher/test_v13/FragmentWithAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityOnlyNeedsPermissionPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithOnNeverAskAgainPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithOnPermissionDeniedPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithShowRationalePermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/Extensions.kt
test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsPermissionsDispatcherTest.kt

I will add test cases for special permission in other PR

Add test cases for Xiaomi and blow M

---

README.md
processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/BaseProcessorUnit.kt

- Fix a few points to tweak code/readme!

Fix a few points to tweak code/readme.

---

README.md

Update travis badge.

---

processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt

- None
- Tweak to define "this" as default param of addRequestPermissionsStatement in kotlin processor unit.

Tweak Kotlin processor unit

---

sample-kotlin/src/main/AndroidManifest.xml
sample-kotlin/src/main/kotlin/permissions/dispatcher/samplekotlin/MainActivity.kt
sample-kotlin/src/main/res/layout/activity_main.xml
sample-kotlin/src/main/res/values/strings.xml
sample/src/main/AndroidManifest.xml
sample/src/main/java/permissions/dispatcher/sample/MainActivity.java
sample/src/main/res/values/strings.xml
sample/src/main/res/values/template-styles.xml

- None
- Somehow we haven't added onDenied and NeverAskAgain annotation for contacts permission in sample app so I added.
- Other than thad did a bit polishment, applied formatter and so on.

Add onDenied and NeverAskAgain annotation for sample

---

lint/src/main/java/permissions/dispatcher/CallOnRequestPermissionsResultDetector.java
lint/src/test/java/permissions/dispatcher/CallOnRequestPermissionsResultDetectorTest.java

- None
- Fix to detect onRequestPermissionsResult more strictly
- currently we allow only calling `super. onRequestPermissionsResult` but that was my mistake so fixed it 🙇
- Tweak other points as well

Fix to detect onRequestPermissionsResult more strictly

---

doc/migration_guide.md

Some touch-ups I made while reading through the migration guide to 3.x.

Small brushstrokes on migration_guide.md

---

processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
processor/src/main/kotlin/permissions/dispatcher/processor/util/Helpers.kt

Related with #376
Haven't resolve the problem with kotlin.String parameter.

Fix syntax error when param exists

---

processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinActivityProcessorUnit.kt
processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt

- Remove ClassName.bestGuess.
- Add `{}  to when expression in OnActivityResult.

Remove ClassName.bestGuess.

---

doc/migration_guide.md

https://github.com/permissions-dispatcher/PermissionsDispatcher/commit/76054106da887827f2d33de04cfcca512c87e815#diff-bda28903b7e2990bd140cb8c36dd51bc broke the top links

Fix migration guide links

---

gradle.properties

- Updated Kotlin from 1.1.51 to 1.2.0
- Updated Gradle from 3.0.0 to 3.0.1
- Updated KotlinPoet from 0.6-snapshot to 0.6
[Update to KotlinPoet 0.6 thanks to @mannodermaus Job](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/389)
[Fix my issue with outdated KotlinPoet version used](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/415)

Update to latest KotlinPoet Version

---

build.gradle
gradle.properties

Clean forgotten Todo in build.graddle

Clean forgotten Todo

---

processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/SystemAlertWindowHelper.kt
processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/WriteSettingsHelper.kt
test/src/main/java/permissions/dispatcher/test/ActivityWithSystemAlertWindow.java
test/src/main/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotations.java
test/src/main/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKt.kt
test/src/main/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotations.kt
test/src/main/java/permissions/dispatcher/test/ActivityWithWriteSetting.java
test/src/main/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotations.java
test/src/main/java/permissions/dispatcher/test/ActivityWithWriteSettingKt.kt
test/src/main/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotations.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotationsTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotationsTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/Extensions.kt
test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt

Fix problem with special permission

---

doc/kotlin_support.md

I confused the setting for kotlin, add the description for kotlin

Add download setting for Kotlin to README

---

build.gradle
lint/src/main/java/permissions/dispatcher/NoDelegateOnResumeDetector.java
lint/src/main/java/permissions/dispatcher/PermissionsDispatcherIssueRegistry.java
lint/src/test/java/permissions/dispatcher/NoDelegateOnResumeDetectorKtTest.kt
lint/src/test/java/permissions/dispatcher/NoDelegateOnResumeDetectorTest.kt

Add a lint rule for not call WithPermissionCheck inside onResume

---

annotation/build.gradle
build.gradle
ext.gradle
gradle.properties
library/build.gradle
processor/build.gradle
scripts/release.sh

Tweak bintray plugin settings to work

---

README.md

ref: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/386#issuecomment-418680789
😇

Add note for Xiaomi support

---

processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt
test/src/main/java/permissions/dispatcher/test/ActivityWithStringParameterKt.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithStringParameterKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotationsTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotationsTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtTest.kt
test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt

ref:https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/427.

workaround to convert java String to kotlin String in argument parameter

---

library/src/main/java/permissions/dispatcher/PermissionUtils.java
test/src/test/java/permissions/dispatcher/test/ActivityOnlyNeedsPermissionPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithOnNeverAskAgainPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithOnPermissionDeniedPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithShowRationalePermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithStringParameterKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/Extensions.kt
test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsPermissionsDispatcherTest.kt

ref: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/544

Drop Xiaomi support

---

processor/src/main/kotlin/permissions/dispatcher/processor/RuntimePermissionsElement.kt
processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/JavaBaseProcessorUnit.kt

https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/473
Addresses https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/556#issuecomment-446736903

Add originating element for generated class

---

gradle.properties

resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/560

Change maven userId

---

doc/maxsdkversion.md

See first sentence at https://permissions-dispatcher.github.io/doc/maxsdkversion.html

Fix maxSdkVersion link and improve text

---

processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt
processor/src/test/java/permissions/dispatcher/processor/util/ExtensionsTest.kt

https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/599 and https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/619 would be resolved by this PR.

Add ByteArray and List workarounds.

---

lint/src/main/java/permissions/dispatcher/CallNeedsPermissionDetector.java
lint/src/test/java/permissions/dispatcher/CallNeedsPermissionDetectorKtTest.kt
lint/src/test/java/permissions/dispatcher/CallNeedsPermissionDetectorTest.kt

- address https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/602
- Fix to use parent class name and method name info to identify method.

602:Improve method identification logic

---

library/src/main/java/permissions/dispatcher/PermissionUtils.java

As we are using `PermissionChecker.checkSelfPermission`, we would want to check against `PermissionChecker.PERMISSION_GRANTED` constant instead.

Use the constant from `PermissionChecker`

---

ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequestFragment.kt

https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/673

fix: retrieve orientation setting when invisible fragment is destroyed

---

ktx/README.md
ktx/src/main/java/permissions/dispatcher/ktx/ActivityExtensions.kt
ktx/src/main/java/permissions/dispatcher/ktx/FragmentExtensions.kt
ktx/src/main/java/permissions/dispatcher/ktx/LocationPermission.kt
ktx/src/test/java/permissions/dispatcher/test/LocationPermissionTest.kt

To address https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/646

feat(ktx): dedicated location permission method

---

lint/src/main/java/permissions/dispatcher/CallOnRequestPermissionsResultDetector.java
lint/src/test/java/permissions/dispatcher/CallOnRequestPermissionsResultDetectorKtTest.kt

Fixes https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/680

fix: support namedMethodReference

---

ktx/src/main/java/permissions/dispatcher/ktx/Event.kt
ktx/src/main/java/permissions/dispatcher/ktx/PermissionRequestViewModel.kt
ktx/src/test/java/permissions/dispatcher/test/EventTest.kt

Address https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/688

fix: wrap PermissionResult with Event

---

ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt

https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/705
Follow https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/705#issuecomment-783299510

fix: use commitAllowingStateLoss to avoid IllegalStateException

---

CHANGELOG.md
doc/migration_guide.md
ktx/README.md
ktx/gradle.properties

Prepare for ktx 1.0.2

---

ktx-sample/build.gradle
ktx/src/main/java/permissions/dispatcher/ktx/PermissionRequestViewModel.kt
ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt
ktx/src/test/java/permissions/dispatcher/test/PermissionRequestViewModelTest.kt

resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/735

fix: avoid leak with ViewModel

---

ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt

resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/734

fix: keep a reference not to release requestFun in KtxPermissionRequest

---

ktx/src/main/java/permissions/dispatcher/ktx/PermissionRequestFragment.kt
ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt

https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/729

fix: sort permissions to secure identification

---

library/src/main/java/permissions/dispatcher/PermissionUtils.java
test/src/test/java/permissions/dispatcher/test/ActivityOnlyNeedsPermissionPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithNoParameterArgumentKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithOnNeverAskAgainPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithOnPermissionDeniedPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithParametersKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithShowRationalePermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotationsTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotationsPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotationsTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtTest.kt
test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/Extensions.kt
test/src/test/java/permissions/dispatcher/test/FragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
test/src/test/java/permissions/dispatcher/test/FragmentWithAllAnnotationsPermissionsDispatcherTest.kt

ref: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/756

fix: use ContextCompat instead of PermissionChecker
