- processor/src/main/kotlin/permissions/dispatcher/processor/impl/BaseProcessorUnit.kt
- processor/src/test/java/permissions/dispatcher/processor/data/Source.java
> Fix problem with @OnNeverAskAgain

- lint/src/main/java/permissions/dispatcher/CallNeedsPermissionDetector.java
- lint/src/main/java/permissions/dispatcher/CallOnRequestPermissionsResultDetector.java
- lint/src/main/java/permissions/dispatcher/PermissionsDispatcherIssueRegistry.java
see #59 and its [comment](https://github.com/hotchemi/PermissionsDispatcher/issues/59#issuecomment-181739420)
Created `CallOnRequestPermissionsResultDetector` that checks following condition:
1. `@RuntimePermissions` exists
1. Find method calls `onRequestPermissionsResult` in `public void onRequestPermissionsResult(int, java.lang.String[], int[])`
1. Check the method call's operand value is XxxPermissionsDispatcher where Xxx is the class name
1. If there is no such method calls in the class, report issue
> Add a lint that checks for calling onRequestPermissionsResult

- processor/src/main/kotlin/permissions/dispatcher/processor/util/Validators.kt
Fixed #109 .
The equality of two MirrorType should be checked by using `Types#isSameType(MirrorType, MirrorType)` .
> Fixed failure when using Kotlin 

- README.md
This commit also fixes a typo (missing s).
resolves #168
> Endorse AA plugin in README

- library/src/main/java/permissions/dispatcher/NeedsPermission.java
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/BaseProcessorUnit.kt
- processor/src/test/java/permissions/dispatcher/processor/ProcessorTestSuite.java
- processor/src/test/java/permissions/dispatcher/processor/data/Source.java
ref: https://github.com/hotchemi/PermissionsDispatcher/issues/192
ref: https://developer.android.com/guide/topics/manifest/uses-permission-element.html
- Add maxSdkVersionSupport.
- Add `maxSdkVersion` in NeedsPermission.java
- If specified value is above 0, processor creates code that only checks SDK_INT and call needs permission method.
- If specified value is 0 or below, it does nothing.
> Support maxSdkVersion

- .travis.yml
- release.sh
- Automate release process by travis ci.
- When tag is pushed travis ci hooks the event and execute `release.sh` automatically.
> Automate releasing to jcenter.

- README.md
> Add @NonNull annotations for onRequestPermissionsResult example

- sample/src/main/java/permissions/dispatcher/sample/camera/CameraPreview.java
- sample/src/main/java/permissions/dispatcher/sample/camera/CameraPreviewFragment.java
Fixed #203 
Just reset Camera instance and some related parameters when re-resumed event is received.
> Fixed A Crash Of Sample App When Sample App Get Back To Foreground

- lint/src/test/java/permissions/dispatcher/BaseLintDetectorTest.java
- lint/src/test/java/permissions/dispatcher/CallNeedsPermissionDetectorTest.java
- lint/src/test/java/permissions/dispatcher/CallOnRequestPermissionsResultDetectorTest.java
- lint/src/test/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetectorTest.java
- I dunno why but test failed on my local
- The reason is we didn't override `allowCompilationErrors` so I add it.
- And also polish some part of test code.
> Fix compile error and polish layout.

- library/src/main/android/permissions/dispatcher/PermissionUtils.java
I hope it doesn't happen in real world, but if `Build.MANUFACTURER` is null, the condition give us NullPointerException. We should avoid the unexpected Exception.
> Handle the case Build.MANUFACTURER = null

- library/src/main/android/permissions/dispatcher/PermissionUtils.java
Close #240
According to https://github.com/a1018875550/PermissionDispatcher/blob/master/library/src/main/android/org.jokar.permissiondispatcher.library/PermissionUtils.java#L129, I think `Build.VERSION_CODES.M` should be included for handling Xiaomi device's runtime permission.
#242 block this pull request. It should fix the problem with test failure.
> Fix the condition of handling Xiaomi phone

- .travis.yml
- README.md
- build.gradle
- deploy_snapshot.sh
- gradle.properties
- gradle/gradle-artifactory-upload.gradle
- library/build.gradle
- processor/build.gradle
Fixes #232 
Changes here include:
- Add a deploy script that uploads snapshots of master to jfrog
- Add SNAPSHOT to current version number of the library
Todo from project maintainer
Since you have a bintray account already you don't have to manually create the OJO account. Follow [this](https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org#DeployingSnapshotstooss.jfrog.org-GettingStartedwithOJO) It's some clicks away.
> Use JFrog's artifactory plugin to upload snaphots

- library/build.gradle
Closes https://github.com/hotchemi/PermissionsDispatcher/issues/255.
`copyJarToOtherModules` method is no longer existing so I removed calling of it.
> Remove un-existing method call.

- README.md
use-permission link didn't show up
> Escape less than and greater than

- README.md
I found that `compile` statement in README cause compile error below.
```
> Could not find method com.github.hotchemi:permissionsdispatcher:2.4.0() for arguments [build_bntcqky9u06m4fd4spdo1j79y$_run_closure4$_closure30@77c02cb] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
When we use closure after the artifact, we should put artifact in parenthesis.
> Fix incorrect compile statement on README

- README.md
* related to #315, Jitpack causes an error when it tries to resolve PD's dependency itself
* users need to change the order of repositories available to their project, so that jcenter takes precedence
> Added a notice for Jitpack users to the README

- processor/src/main/kotlin/permissions/dispatcher/processor/PermissionsProcessor.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/BaseProcessorUnit.kt
The annotation processor uses a RequestCodeProvider to assign unique
request codes to each annotated @NeedsPermission method. This shared
state collides with the non-deterministic nature of the processor's
RoundEnvironment, since we can't guarantee the processing order by default.
Here, we sort the affected sets of data before starting the iterations.
First, the annotated @RuntimePermissions classes need to be in the same
order every time we build. Second, inside each annotated class, the
annotated @NeedsPermission methods also need to be in the same order.
Using simple "sortedBy" predicates, this is achieved.
fixes #318 
---
Im unsure if it's possible to unit test this. We could implement JUnit's `@Repeat` with a less trivial set of inputs, and check that the output is the same every …
> Allow for Deterministic, Reproducible Builds with sorted inputs

- lint/src/main/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetector.java
It's just a small tiny change, it seems UAST can extract annotation info more precisely so we don't have to define two candidates!
> Fix to define expected method name as String

- lint/src/main/java/permissions/dispatcher/CallNeedsPermissionDetector.java
- lint/src/test/java/permissions/dispatcher/CallNeedsPermissionDetectorTest.java
- None
- I found that `CallNeedsPermissionDetector` lint check hasn't been working since around 2.2.0... 😢
- The reason is basically somehow we missed [these logics](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/2.2.0/lint/src/main/java/permissions/dispatcher/CallNeedsPermissionDetector.java#L97-L109) which actually detect illegal method call.
- Actually unit test cases were weird and that's why we couldn't notice that.
- So I fixed both the logic itself and test case.
> Fix CallNeedsPermissionDetector

- lint/src/main/java/permissions/dispatcher/CallNeedsPermissionDetector.java
- lint/src/test/java/permissions/dispatcher/CallNeedsPermissionDetectorTest.java
addresses https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/377
- Fix to detect @NeedsPermission annotated method calling when the receiver of the method is null.
- Otherwise if activity/fragment calls the same method name as NeedsPermission annotated one lint flags it incorrectly.
> Fix the way of detecting @NeedsPermission annotated method calling

- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt
- https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/376
- kotlin.String converts to java.lang.String
- Add temporal extension method which converts java.lang.String to kotlin.String.
- This is arguably a bug of KotlinPoet so we're going to file a bug report!
> Add temporal extension method which converts java.lang.String to kotlin.String

- README.md
migration guide link was pointing to Kotlin support info.
> Fix incorrect link to migration guide

- .travis.yml
- gradle.properties
- processor/src/main/kotlin/permissions/dispatcher/processor/PermissionsProcessor.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/ProcessorUnits.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/JavaActivityProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/JavaBaseProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/JavaNativeFragmentProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/JavaSupportFragmentProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinActivityProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinNativeFragmentProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinSupportFragmentProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt
- test-v13/src/main/java/permissions/dispatcher/test_v13/FragmentWithAllAnnotationsKt.kt
- test-v13/src/test/java/permissions/dispatcher/test_v13/FragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
Generated Kotlin code needs to honor nullable parameters in the signatures of annotated `@NeedsPermission` methods:
```kotlin
@RuntimePermissions
class SomeActivity : AppCompatActivity() {
@NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION)
fun updateLocation(currentLocation: LatLng?) {
// ...
}
}
// Wrong
fun SomeActivity.updateLocationWithPermissionCheck(currentLocation: LatLng) {
}
// Correct
fun SomeActivity.updateLocationWithPermissionCheck(currentLocation: LatLng?) {
}
```
As part of the Parameter-to-TypeName chain, we now inspect the annotations of a `VariableElement` & attach the nullability information to its `TypeName` via a new extension method, `mapToNullableTypeIf(Boolean)`. Since we use this chain in multiple places, I have extracted this mapping into its own …
> Honor nullable params in Kotlin

- lint/src/main/java/permissions/dispatcher/CallOnRequestPermissionsResultDetector.java
It seems if the project is only consist Java, then `KotlinUQualifiedReferenceExpression` become `NoClassDefFoundError`. 
TBH, I can't find a best way to fix this problem.
> Fix the problem with NoClassDefFoundError

- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
This way Java code can simply call the generated methods,
without appending `Kt` to end of the generated class name.
This should fix https://github.com/permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin/issues/15 .
> Add JvmName annotation to generated file

- test/src/test/java/permissions/dispatcher/test/ActivityOnlyNeedsPermissionPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithOnNeverAskAgainPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithOnPermissionDeniedPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithShowRationalePermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotationsTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotationsTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsPermissionsDispatcherTest.kt
resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/455
Inspired by eclipse/hono#145.
occasionally we've suffered `NeverWantedButInvoked` from mockito only on TravisCI.. 🤔
I've tried many points and finally avoiding keeping activity/fragment as a member variable somehow address the problem..I tried building 10 times on TravisCi but seemingly never fails.. 😅
> Fix intermittent failure of test project

- lint/src/main/java/permissions/dispatcher/CallOnRequestPermissionsResultDetector.java
- lint/src/test/java/permissions/dispatcher/CallNeedsPermissionDetectorKtTest.kt
- lint/src/test/java/permissions/dispatcher/CallOnRequestPermissionsResultDetectorKtTest.kt
- lint/src/test/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetectorKtTest.kt
resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/373
- Add kotlin test cases for lint module.
- Tweak CallOnRequestPermissionsResultDetector to address onRequestPermissionsResult extension function.
> Add kotlin test cases for lint module

- test-v13/build.gradle
- test-v13/src/test/java/permissions/dispatcher/test_v13/Extensions.kt
- test-v13/src/test/java/permissions/dispatcher/test_v13/FragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test-v13/src/test/java/permissions/dispatcher/test_v13/FragmentWithAllAnnotationsPermissionsDispatcherTest.kt
- test/build.gradle
- test/src/test/java/permissions/dispatcher/test/ActivityOnlyNeedsPermissionPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithOnNeverAskAgainPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithOnPermissionDeniedPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithShowRationalePermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotationsTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotationsTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/Extensions.kt
- test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/SupportFragmentWithAllAnnotationsPermissionsDispatcherTest.kt
The problem was it set `Build.MANIFACTURE` using reflection https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/980c35ed396ce7d896c69b2b862923e38b7af11f/test/src/test/java/permissions/dispatcher/test/Extensions.kt#L73-L81 and did not clear the value. So, that since `Build.MANIFACTURE` is xiaomi, https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/39c665901c0b293182be8b236a1524807dbca2b1/library/src/main/java/permissions/dispatcher/PermissionUtils.java#L94-L97 `hasSelfPermissionForXiaomi` get called and the tests fail.
This happens when xiaomi related tests get executed before testing OnShowRationale related tests.
You can reproduce this issue in local machine if https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/f0f55196dea473eb9dbe729f06 …
> Make CI stable, again

- lint/src/main/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetector.java
- lint/src/test/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetectorKtTest.kt
- lint/src/test/java/permissions/dispatcher/NoCorrespondingNeedsPermissionDetectorTest.kt
The problem is it validated each time lint found annotation. This commit
make lint validate the annotation at afterVisitClass since at the point,
all annotations are stored into needsPermissionsAnnotations and
onShowRationaleAnnotations variables.
Close #407
> Fix the problem with order matter "Useless @OnShowRationale declaration"

- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinActivityProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinNativeFragmentProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinSupportFragmentProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/SensitivePermissionInterface.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/SystemAlertWindowHelper.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/WriteSettingsHelper.kt
This problem seems to have happened because `android.support.v4.app.Fragment.getActivity()` is specified as nullable.
And I also fix #429.
> Fix compile error when request SYSTEM_ALERT_WINDOW on SupportFragment

- processor/src/main/kotlin/permissions/dispatcher/processor/RuntimePermissionsElement.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/exception/SpecialPermissionsWithNeverAskAgainException.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/util/Validators.kt
- processor/src/test/java/permissions/dispatcher/processor/ProcessorTestSuite.java
- processor/src/test/java/permissions/dispatcher/processor/data/Source.java
- test/src/main/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotations.java
- test/src/main/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotations.kt
- test/src/main/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotations.java
- test/src/main/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotations.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithSystemAlertWindowKtAllAnnotationsTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ActivityWithWriteSettingKtAllAnnotationsTest.kt
resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/436
This PR adds compile time validation for detecting `OnNeverAskAgain` declaration with 'WRITE_SETTINGS' or 'SYSTEM_ALERT_WINDOW' to address https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/436.
> compile time validation for detecting OnNeverAskAgain with special permissions

- gradle.properties
- processor/build.gradle
- processor/src/main/kotlin/permissions/dispatcher/processor/exception/WrongClassException.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/ProcessorUnits.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/java/JavaConductorProcessorUnit.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinConductorProcessorUnit.kt
- processor/src/test/java/permissions/dispatcher/processor/ProcessorTestSuite.java
- processor/src/test/java/permissions/dispatcher/processor/data/Source.java
- test/build.gradle
- test/src/main/java/permissions/dispatcher/test/ConductorWithAllAnnotations.java
- test/src/main/java/permissions/dispatcher/test/ConductorWithAllAnnotationsKt.kt
- test/src/test/java/permissions/dispatcher/test/ConductorControllerWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ConductorWithAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/Extensions.kt
resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/496
This PR contains [Conductor](https://github.com/bluelinelabs/Conductor) library support.
The diff is actually smaller than I expected. Just added `JavaConductorProcessorUnit` and `KotlinConductorProcessorUnit` as new processors and remaining diff is test code.
What do you think?
> Conductor support

- test/src/test/java/permissions/dispatcher/test/ConductorControllerWithAllAnnotationsKtPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/ConductorWithAllAnnotationsPermissionsDispatcherTest.kt
- test/src/test/java/permissions/dispatcher/test/Extensions.kt
Fixes:
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced argument matcher detected here:
-> at permissions.dispatcher.test.ExtensionsKt.mockShouldShowRequestPermissionRationaleConductorController(Extensions.kt:83)
You cannot use argument matchers outside of verification or stubbing.
```
> Fix Conductor tests

- processor/src/main/kotlin/permissions/dispatcher/processor/PermissionsProcessor.kt
- processor/src/main/kotlin/permissions/dispatcher/processor/impl/kotlin/KotlinBaseProcessorUnit.kt
Depends on #625, https://github.com/permissions-dispatcher/kompile-testing/pull/13
Will add some tests later.
> Incremental annotation processing for Kotlin

- ktx/src/main/java/permissions/dispatcher/ktx/PermissionRequestViewModel.kt
- ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt
Currently, we allow multiple observers to receive the permission change event but it might cause an unexpected issue.
ref: https://github.com/yt-tkhs/permissionsdispatcher-ktx-issue
> fix(ktx): allow only 1 observer to receive the event
